-- arock-log.org_log: an org file kept on the log, read back from the fold, rebuilt exactly, refused whole.
local spec = require("mono.spec")
local alog = require("arock-log")
local org_log = require("arock-log.org_log")
local sqlite = require("arock-log.ffi")

local function fresh()
  return alog.open(sqlite.open(":memory:"), { clock = function() return "2026-10-02T12:00:00Z" end })
end

local function count(s) return s.db:exec("select count(*) as n from events")[1].n end

spec.test("a write is kept as events and read back with what the host stamps", function()
  local s = fresh()
  local text = assert(org_log.write(s, "org/plants.org", "#+TITLE: plants\n\n* TODO Water the fern\n* Buy soil\n"))
  spec.ok(text:find(":ID: e1", 1, true)); spec.ok(text:find(":ID: e2", 1, true))
  spec.ok(text:find("#+TITLE: plants", 1, true))
  local kinds = {}
  for _, e in ipairs(s:events()) do kinds[#kinds + 1] = e.keyword end
  spec.eq(table.concat(kinds, ","), "Add Entry,Add Entry,Set Header")
  local done = assert(org_log.write(s, "org/plants.org", (text:gsub("TODO Water", "DONE Water"))))
  spec.ok(done:find("CLOSED: [2026-10-02 Fri 12:00]", 1, true))
  spec.eq(org_log.read(s, "org/plants.org"), done)
end)

spec.test("the fold rebuilds exactly, from the start and from a snapshot", function()
  local s = fresh()
  local text = assert(org_log.write(s, "org/a.org", "* TODO one\n* two\n"))
  text = assert(org_log.write(s, "org/a.org", (text:gsub("TODO one", "DONE one"))))
  s:snapshot()
  local swapped = text:gsub("(%* DONE one.-)(%* two.*)$", "%2\n%1")
  text = assert(org_log.write(s, "org/a.org", swapped))
  s:rebuild()
  spec.eq(org_log.read(s, "org/a.org"), text)
  s.db:exec("delete from snapshots")
  s:rebuild()
  spec.eq(org_log.read(s, "org/a.org"), text)
end)

spec.test("a forged or history-rewriting edit is refused whole, by line, and keeps nothing", function()
  local s = fresh()
  local text = assert(org_log.write(s, "org/a.org", "* DONE paid\n* TODO next\n"))
  local before = count(s)
  local forged = text:gsub("CLOSED: %[2026%-10%-02 Fri 12:00%]", "CLOSED: [2026-09-01 Tue]"):gsub("TODO next", "DONE next")
  local out, errs = org_log.write(s, "org/a.org", forged)
  spec.eq(out, nil)
  spec.eq(errs[1].line, 1); spec.ok(errs[1].msg:find("CLOSED is history", 1, true))
  spec.eq(count(s), before, "nothing was appended")
  spec.eq(org_log.read(s, "org/a.org"), text)
  local granted, gerrs = org_log.write(s, "org/b.org", "* w\n:PROPERTIES:\n:GRANTED: 2026-10-02\n:END:\n")
  spec.eq(granted, nil); spec.ok(gerrs[1].msg:find("GRANTED is written by the host", 1, true))
  spec.ok(org_log.write(s, "org/b.org", "* w\n:PROPERTIES:\n:GRANTED: 2026-10-02\n:END:\n", { actor = "host" }))
end)

spec.test("links resolve against the log and the computer's files", function()
  local s = fresh()
  assert(org_log.write(s, "org/a.org", "* one\n"))
  s:append("t", "Write File", { "files/report.pdf", "%PDF" }, "agent")
  spec.ok(org_log.write(s, "org/b.org", "* see [[id:e1]] and [[file:files/report.pdf]]\n"))
  local _, errs = org_log.write(s, "org/c.org", "* see [[file:files/missing.pdf]]\n")
  spec.ok(errs[1].msg:find("names no file", 1, true))
  local _, e2 = org_log.write(s, "org/c.org", "* see [[org:fern/none]]\n",
    { resolve = function(t) return false, "the address " .. t .. " names nothing" end })
  spec.eq(e2[1].msg, "the address org:fern/none names nothing")
end)

spec.test("an undone edit goes back to the text before it", function()
  local s = fresh()
  local text = assert(org_log.write(s, "org/a.org", "* TODO one\n"))
  assert(org_log.write(s, "org/a.org", (text:gsub("TODO one", "TODO one, renamed"))))
  local last = s:events()
  s:undo(last[#last].seq, "user")
  spec.eq(org_log.read(s, "org/a.org"), text)
end)

spec.test("Decide, Grade and Outcome are declared, a decision with its options", function()
  local s = fresh()
  s:append("t", "Decide", { "org:fern/tasks/e1", "jev", "weather|triage|ask", "weather", "0.82" }, "host")
  s:append("t", "Grade", { "org:fern/tasks/e1", "on track", "0.7" }, "host")
  s:append("t", "Outcome", { "org:fern/tasks/e1", "green" }, "host")
  spec.err(function() s:append("t", "Decide", { "org:fern", "jev" }, "host") end, "Decide takes")
  local f = alog.fields(s:events()[1])
  spec.eq(f.options, "weather|triage|ask"); spec.eq(f.choice, "weather")
end)

spec.test("an empty file is kept as nothing, and read back as empty", function()
  local s = fresh()
  spec.eq(org_log.write(s, "org/empty.org", ""), "")
  spec.eq(count(s), 0)
end)

spec.run()
