defmodule MossWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :moss

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_moss_key",
    signing_salt: "wK+U7knZ",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :moss,
    gzip: not code_reloading?,
    only: MossWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Shroomi's pinned assets, the only scripts and styles an app's page loads (Moss.Computer.App)
  plug Plug.Static,
    at: "/shroomi",
    from: Path.join(Application.compile_env!(:moss, :core), "submodules/shroomi/assets"),
    only_matching: ~w(htmx basecoat shroomi)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: {__MODULE__, :log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MossWeb.Router

  @doc "A request's log level: none for an app's window, whose path holds its cap (MossWeb.Frame)."
  def log_level(%{path_info: ["computers", _, "frame" | _]}), do: false
  def log_level(_), do: :info
end
